site_name: flet-orbit
site_url: https://flet-orbit.gabover.se
theme:
  name: material
  logo: assets/img/flet-orbit-isotype.png
  favicon: assets/img/flet-orbit-isotype.png
  palette:
    primary: custom
extra_css:
  - stylesheets/extra.css
nav:
  - fletflow: index.md
  - Getting Started: getting-started.md
  - Project Structure: project-structure.md
  - Makefile: makefile.md
